- hosts: all
  gather_facts: no
  tasks:
  - win_domain_membership:
      dns_domain_name: proconnect.local
      hostname: 3.239.52.169
      domain_admin_user: vinayak@proconnect.local
      domain_admin_password: {{ lookup('hashi_vault', 'secret=secrets/creds/win-ad-cred:value auth_method=approle role_id=effb9c04-5ac9-254d-8f0e-7ea6d59a6a7a secret_id=028dc907-2fed-ac74-c40c-e265fe9bbf65 url=http://10.21.34.85:8200')}}"
      domain_ou_path: "DC=proconnect,DC=local"
      state: domain
    register: domain_state
  - win_reboot:
    when: domain_state.reboot_required
