---
 - hosts: all
   tasks:
       - name: Print all available facts
         ansible.builtin.debug:
           var: ansible_facts
       - name: date and time
         vars:
           msg: |
             Hostname: {{ ansible_hostname }}
         debug:
            msg: "{{ msg.split('\n') }}"
