---
- name: Fetch Secret from Vault
  hosts: localhost
  vars:
    secret_var: "{{ lookup('hashi_vault', 'secret=secret/data/creds token=proconnect url=http://54.235.206.14:8200') }}"
  tasks:
    - name: Display Secret
      debug:
        msg: "{{ secret_var.data.secret }}"

