- hosts: localhost
  tasks:
    - name: Fetch secret from Vault
      vars:
        secret_path: secret/creds
        vault_addr: http://54.235.206.14:8100/
        vault_token: root
      set_fact:
        secret: "{{ lookup('hashi_vault', 'secret=' + secret_path + ' token=' + vault_token + ' url=' + vault_addr) }}"
    - name: Display secret
      debug:
        msg: "{{ secret }}"
