---
- name: Fetch OS Details
  hosts: localhost  # Replace with the appropriate host or group of hosts
  gather_facts: yes   # This gathers facts about the target hosts, including OS details

  tasks:
    - name: Display OS Facts
      debug:
        var: ansible_facts['ansible_distribution']
        
    - name: Display OS Version
      debug:
        var: ansible_facts['ansible_distribution_version']
        
    - name: Display OS Family
      debug:
        var: ansible_facts['ansible_os_family']

