- name: "Windows Firewall"
  hosts: all
  tasks:
    - name: "Set DNS Client"
      win_dns_client:
          adapter_names: Ethernet
          ipv4_addresses:
          - 3.239.52.169
      register: dns_details
    
    - name: "Join Domain"
      win_domain_membership:
        dns_domain_name: proconnect.local
        hostname: "{{  ansible_hostname }}"
        domain_admin_user: vinayak@proconnect.local
        domain_admin_password: "Taashee@123"
        state: domain
      register: domain_state
    - win_reboot:
      when: domain_state.reboot_required

    - name: Add a local and domain user to a local group
      win_group_membership:
        name: Remote Desktop Users
        members:
           - proconnect\vinayak
        state: present

          #- name: Download Tomcat  
          #win_get_url:
          #url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71-windows-x64.zip
          #dest: C:\tomcat.zip    
          #- name: Unzip Tomcat
          #win_unzip:
          #src: C:\tomcat.zip
          #dest: C:\Program Files    
          #- name: Set Environment Variable
          #win_environment:
          #name: CATALINA_HOME
          #value: C:\Program Files\apache-tomcat-9.0.71
        #level: process
        #- name: Start Tomcat as a Service
        #win_shell: "{{ CATALINA_HOME }}\\bin\\service.bat install"
        #register: result
        # - name: Check Service Status
        #win_shell: "sc queryex ApacheTomcat9"
        #win_shell: tomcat_status    
        #- name: Debug Service Status
        #debug:
        #var: tomcat_status.stdout_lines
