---
- name: Install Apache HTTP Server (httpd) on Amazon Linux
  hosts: all 
  tasks:
    - name: Update the System Packages
      dnf:
        name: "*"
        state: latest

    - name: Install Apache HTTP Server (httpd)
      dnf:
        name: httpd
        state: present

    - name: Start and Enable httpd service
      systemd:
        name: httpd
        state: started
        enabled: yes
        daemon_reload: yes

