---
- name: "Windows Firewall"
  hosts: all
  gather_facts: true
  become: false
  vars:
    groups: "{{ groups | map('to_string') | list }}"  # Ensures groups is a list of strings

  tasks:
    - name: "Gather Network Interfaces"
      win_shell: Get-NetAdapter | Select-Object -ExpandProperty Name
      register: network_interfaces

    - name: "Set DNS Client"
      win_dns_client:
        adapter_names: "{{ network_interfaces.stdout_lines | join(',') }}"
        ipv4_addresses:
          - "{{ ip_address }}"
      register: dns_details

    - name: "Join Domain"
      win_domain_membership:
        dns_domain_name: "{{ ad_domain_name }}"
        hostname: "{{ ansible_hostname }}"
        domain_admin_user: "{{ ad_admin_user }}"
        domain_admin_password: "{{ ad_admin_password }}"
        state: domain
      register: domain_state

    - win_reboot:
      when: domain_state.reboot_required
    - name: Debug groups variable
      debug:
        msg: "The value of 'groups' is: {{ groups }}"
    - name: Add AD Group
      win_group_membership:
        name: Remote Desktop Users
        members: "{{ groups | list }}"
        state: present
