---
- name: Install Apache HTTP Server (httpd) on Ubuntu
  hosts: all
  gather_facts: no  # Disable facts so the playbook can run
  tasks:

    - name: Ensure python3 and python3-six are installed
      raw: |
        sudo apt update -y
        sudo apt install -y python3 python3-pip python3-six || sudo pip3 install six
      changed_when: false

    - name: Gather facts manually after fixing Python
      setup:

    - name: Update the System Packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Apache HTTP Server (httpd)
      apt:
        name: apache2
        state: present

    - name: Start and Enable httpd service
      systemd:
        name: apache2
        state: started
        enabled: yes
        daemon_reload: yes
